// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// device信息表
type DeviceInfo struct {
	ID         int64     `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 唯一自增主键ID
	DeviceID   string    `gorm:"column:device_id;NOT NULL"`            // device提供的ID
	GPUType 	string    `gorm:"column:gpu_type;NOT NULL"`          // gpu type
	Notes 	   string    `gorm:"column:notes;NOT NULL"`          		// 备注
	IsDelete 	int       `gorm:"column:is_delete;default:0;NOT NULL"` // 是否删除
	CreateAt   time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt   time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *DeviceInfo) TableName() string {
	return "device_info"
}

