// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

type LabelInfo struct {
	Id       int64     `gorm:"column:id;primary_key" json:"id"`
	Name     string    `gorm:"column:name;NOT NULL" json:"name"`
	Notes    string    `gorm:"column:notes;NOT NULL" json:"notes"`
	TID      int64     `gorm:"column:tid;default:0;NOT NULL" json:"tid"`
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *LabelInfo) TableName() string {
	return "label_info"
}
