// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// 渲染等级表
type PlInfo struct {
	ID             int            `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Pl             string         `gorm:"column:pl;NOT NULL"`           // 渲染等级
	PlName         string         `gorm:"column:pl_name;NOT NULL"`      // 渲染等级
	ServiceType    string         `gorm:"column:service_type;NOT NULL"` // 渲染名称
	TerminalDevice TerminalDevice `gorm:"column:terminal_device;NOT NULL"`
	AvgFrameRate   string         `gorm:"column:avg_frame_rate;NOT NULL"`
	Priority       int            `gorm:"column:priority;default:0;NOT NULL"`
	Notes          string         `gorm:"column:notes;NOT NULL"`
	Games          string         `gorm:"column:games;NOT NULL"`
	CreateAt       time.Time      `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt       time.Time      `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *PlInfo) TableName() string {
	return "pl_info"
}

type TerminalDevice string

const (
	PCTerminalDevice     TerminalDevice = "PC"
	MOBILETerminalDevice TerminalDevice = "MOBILE"
)
