// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// 区域配置表
type RegionConfig struct {
	RegionCode           string    `gorm:"column:region_code;primary_key"`                    // area code
	StunUrl              string    `gorm:"column:stun_url;NOT NULL"`                          // ICE打洞服务器地址
	SysRestartInterval   int       `gorm:"column:sys_restart_interval;default:60;NOT NULL"`   // 系统重启间隔
	ArsHeartbeatInterval int       `gorm:"column:ars_heartbeat_interval;default:60;NOT NULL"` // ars发送心跳间隔
	HttpPingUrl          string    `gorm:"column:http_ping_url;NOT NULL"`
	SpeedUrl             string    `gorm:"column:speed_url;default:测速地址;NOT NULL"` // 测速地址
	IdxUrl               string    `gorm:"column:idx_url;NOT NULL"`                // idx接入地址
	LogSvcUrl            string    `gorm:"column:log_svc_url;NOT NULL"`            // logSvc地址
	CreateAt             time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt             time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *RegionConfig) TableName() string {
	return "region_config"
}

