// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// idc region info
type RegionIdcInfoCrm struct {
	ID              int       `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	ZoneRegionCode  string    `gorm:"column:zone_region_code;NOT NULL"`   // zone code
	RegionCode string    `gorm:"column:region_code;NOT NULL"`        // price code
	IdcRegionCode      string    `gorm:"column:idc_region_code;NOT NULL"`    // area code
	RegionName      string    `gorm:"column:region_name;NOT NULL"`        // area name
	IdcType         IdcType   `gorm:"column:idc_type;default:0;NOT NULL"` // 0:edge机房 1：idc机房
	Description     string    `gorm:"column:description;NOT NULL"`        // descriton
	GatewayUrl      string    `gorm:"column:gateway_url;NOT NULL"`        // 区域接入网关地址
	MatchRegular    string    `gorm:"column:match_regular;NOT NULL"`      // IP地址库匹配出来的字符和所属地域的匹配规则
	IdcAddr         string    `gorm:"column:idc_addr;NOT NULL"`
	IdcGps          string    `gorm:"column:idc_gps;NOT NULL"`
	AsDefaultRegion int       `gorm:"column:as_default_region;default:0;NOT NULL"` // 0为非默认地址，1为默认地址，唯一
	CreateAt        time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt        time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *RegionIdcInfoCrm) TableName() string {
	return "region_idc_info"
}
