// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// zone info
type RegionZoneInfo struct {
	ID          int       `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	RegionCode  string    `gorm:"column:region_code;NOT NULL"` // area code
	RegionName  string    `gorm:"column:region_name;NOT NULL"` // area name
	Description string    `gorm:"column:description;NOT NULL"` // descriton
	GatewayUrl  string    `gorm:"column:gateway_url;NOT NULL"` // gateway url
	CreateAt    time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt    time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *RegionZoneInfo) TableName() string {
	return "region_zone_info"
}

