// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"

	libModel "github.com/2JYK2/go-lib/models"
)

// host info
type ResourceScan struct {
	Rid        int64  `gorm:"column:rid;primary_key;AUTO_INCREMENT;NOT NULL"`
	Tid        int64  `gorm:"column:tid;default:0;NOT NULL"` // Owning tenant ID, that is, the Id of the mine owner
	RegionCode string `gorm:"column:region_code;NOT NULL"`   // Host area
	Spec       string `gorm:"column:spec;NOT NULL"`          // Spec code
	Location   string `gorm:"column:location;NOT NULL"`      // Host country
	Number     int    `gorm:"column:number"`
}

type Resource struct {
	Rid              int64                 `gorm:"column:rid;primary_key;AUTO_INCREMENT;NOT NULL"`
	Tid              int64                 `gorm:"column:tid;default:0;NOT NULL"`             // Owning tenant ID, that is, the Id of the mine owner
	Name             string                `gorm:"column:name;NOT NULL"`                      // Host Name
	TenantName       string                `gorm:"column:tenant_name;NOT NULL"`               // Tenant Whole Sale Set Name
	Fingerprint      string                `gorm:"column:fingerprint;NOT NULL"`               // 兼容部署策略//TODO 后续部署任务通过iaas下发就可以废弃
	AliasName        string                `gorm:"column:alias_name;NOT NULL"`                // alias name(not update)
	ZoneCode         string                `gorm:"column:zone_code;NOT NULL"`                 // zone region code
	RegionCode       string                `gorm:"column:region_code;NOT NULL"`               // Host area
	IdcCode          string                `gorm:"column:idc_code;NOT NULL"`                  // IDC region
	Sn               string                `gorm:"column:sn;NOT NULL"`                        // Sn
	HostDevSn        string                `gorm:"column:host_dev_sn;NOT NULL"`               // host_devsn
	Mac              string                `gorm:"column:mac;NOT NULL"`                       // mac（兼容之前呢的数据）
	ResourcePool     ResourcePool          `gorm:"column:resource_pool;default:IDC;NOT NULL"` // Resource pool [IDC, HE,EDGE]
	ResourceType     libModel.ResourceType `gorm:"column:resource_type;NOT NULL"`             // host、container、benchmark
	BizType          int                   `gorm:"column:biz_type;default:0;NOT NULL"`        // Business type[0:ARS 1:Ai]
	OsType           libModel.OsType       `gorm:"column:os_type;default:windows;NOT NULL"`   // Operating system type [windows,android]
	AgentStartTs     int64                 `gorm:"column:agentStartTs;default:0;NOT NULL"`    // agent start ts
	LocalIP          string                `gorm:"column:local_ip;NOT NULL"`                  // local  ip
	Healthy          int                   `gorm:"column:healthy;default:0;NOT NULL"`         // Healthy status [0:false,1:true]
	LastHealthTs     int                   `gorm:"column:last_health_ts;default:0;NOT NULL"`  // Last health ts （Unit/time stamp）
	WholeSaleTid     int64                 `gorm:"column:whole_sale_tid;default:0;NOT NULL"`  // Wholse sale tid
	Online           int                   `gorm:"column:online;default:0;NOT NULL"`          // [0 unstake, 1 staked】
	OnboardingStatus OnboardingStatus      `gorm:"column:onboarding_status;default:0;NOT NULL"`
	Spec             string                `gorm:"column:spec;NOT NULL"`                       // Spec code
	OldSpec          string                `gorm:"column:old_spec;NOT NULL"`                   // Spec code
	Label            string                `gorm:"column:label;NOT NULL"`                      // 标签
	OrderCode        string                `gorm:"column:order_code;default:0;NOT NULL"`       // Order code
	NetIP            string                `gorm:"column:net_ip;NOT NULL"`                     // Net in ip
	NetPort          int                   `gorm:"column:net_port;"`                           // Net  port
	GroupId          int64                 `gorm:"column:gid;"`                                // group id
	NetType          int                   `gorm:"column:net_type;default:0;NOT NULL"`         //
	Location         string                `gorm:"column:location;NOT NULL"`                   // Host country
	Longitude        string                `gorm:"column:longitude;NOT NULL"`                  // Host lon
	Latitude         string                `gorm:"column:latitude;NOT NULL"`                   // Host lat
	Status           ResourceStatus        `gorm:"column:status;default:Idle;NOT NULL"`        // host state
	StatusChangeAt   int64                 `gorm:"column:status_change_at;default:0;NOT NULL"` // host state change ts
	Md5              string                `gorm:"column:md5;NOT NULL"`                        // sys info md5
	Tag              int                   `gorm:"column:tag;default:0;NOT NULL"`              // 0:register 1:inject
	ChangeStatus     bool                  `gorm:"column:change_status;default:0;NOT NULL"`    // 0:register 1:inject
	//BandwidthLevel   string         `gorm:"column:bandwidth_level;default:0;NOT NULL"`  // 0:register 1:inject
	CreateAt         time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt         time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	ChangeAt         time.Time `gorm:"column:change_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	ResourceLockCode string    `gorm:"-"`
}

func (m *Resource) TableName() string {
	return "resource"
}

const ResourceTableName = "resource"

type ResourceStatus = string

const (
	ResourceStatusForPreparing ResourceStatus = "preparing"
	ResourceStatusForInService ResourceStatus = "in-service"
	ResourceStatusForIdle      ResourceStatus = "idle"
	ResourceStatusForError     ResourceStatus = "error"
)

type ResourcePool string

const (
	IDC  ResourcePool = "IDC"
	NODE ResourcePool = "NODE"
	HE   ResourcePool = "HE"
)

type OnboardingStatus = int

var OnboardingStatusText = map[OnboardingStatus]string{
	PrepareOnboardingStatus:              "Registration successful. Preparing your environment…",
	RegistrationLocationOnboardingStatus: "Registration failed. Location not supported for registration. ",
	ResourceNotHostStatus:                "Registration failed. Only bare metal machines are supported for registration.",
	NoGPUOnboardingStatus:                "Registration failed. No GPU detected on the resource.",
	GPUTypeNotUniqueOnboardingStatus:     "Registration failed. Multiple GPU types detected — all GPUs must be identical.",
	UnsupportedOSOnboardingStatus:        "Registration failed. Unsupported OS version (Supported: Ubuntu 20.04/22.04 LTS).",
	SpecMismatchOnboardingStatus:         "Registration failed. Specification mismatch — please contact support.",
	IPCheckFailedOnboardingStatus:        "Machine ingress failed. Please check your network or IP settings. ",
	SystemCheckingOnboardingStatus:       "Environment ready. Running system check…",
	SpecCheckFailedOnboardingStatus:      "Specification checking failed.",
	StakingPendingOnboardingStatus:       "System check complete! You can now stake your GPUs and start earning.",
}

const (
	PrepareOnboardingStatus              OnboardingStatus = 0  // 正在准备中
	RegistrationLocationOnboardingStatus OnboardingStatus = 1  // 城市禁止注册
	ResourceNotHostStatus                OnboardingStatus = 2  // 资源不是 Host
	NoGPUOnboardingStatus                OnboardingStatus = 3  // 没有 GPU
	GPUTypeNotUniqueOnboardingStatus     OnboardingStatus = 4  // GPU 类型不唯一
	UnsupportedOSOnboardingStatus        OnboardingStatus = 5  // 操作系统不支持：仅限 Ubuntu20/22 或 Android
	SpecMismatchOnboardingStatus         OnboardingStatus = 6  // 无法匹配规格
	IPCheckFailedOnboardingStatus        OnboardingStatus = 7  // IP 检查失败
	SystemCheckingOnboardingStatus       OnboardingStatus = 8  // 系统检查中
	SpecCheckFailedOnboardingStatus      OnboardingStatus = 9  // 规格检查失败
	StakingPendingOnboardingStatus       OnboardingStatus = 10 // 待质押

)
const (
	PreparingStatus              = "Preparing Environment"
	AdditionalInfoRequiredStatus = "Additional Info Required"
	SystemCheckInProgressStatus  = "System Check in Progress"
	CheckFailedStatus            = "Check Failed"
	StakingPendingStatus         = "Staking Pending"
	StakedStatus                 = "Staked"
	UnstakedStatus               = "Unstaked"
	OnlineStatus                 = "Online"
	OfflineStatus                = "Offline"
	OrderReservedStatus          = "Reserved"
	OrderIdleStatus              = "Idle"
)

//var CheckStatusToErrorMsg = map[int]string{
//	1: "No GPU Card",
//	2: "GPU Card Type is Not Unique",
//	3: "Unable to Match Specifications",
//	5: "Specification Checking Failed",
//}

var CheckStatusString = map[int]string{
	0: "Preparing",
	1: "Resources None GPU",
	2: "Resource GPU Not Unique",
	3: "Specification Mismatch",
	4: "Checking",
	5: "Check Fail",
	6: "Check Pass",
}

func (m *Resource) GetOrderStatus() string {
	if m.OrderCode != "0" && m.OrderCode != "" {
		return "Reserved"
	}
	return "Idle"

}

func (m *Resource) GetOnborading() string {
	if m.OnboardingStatus == StakingPendingOnboardingStatus {
		if m.Online == 1 {
			return StakedStatus
		} else {
			return StakingPendingStatus
		}
	}

	if m.OnboardingStatus == RegistrationLocationOnboardingStatus ||
		m.OnboardingStatus == ResourceNotHostStatus ||
		m.OnboardingStatus == NoGPUOnboardingStatus ||
		m.OnboardingStatus == GPUTypeNotUniqueOnboardingStatus ||
		m.OnboardingStatus == UnsupportedOSOnboardingStatus ||
		m.OnboardingStatus == SpecMismatchOnboardingStatus ||
		m.OnboardingStatus == SpecCheckFailedOnboardingStatus {
		return CheckFailedStatus
	}
	if m.OnboardingStatus == IPCheckFailedOnboardingStatus {
		return AdditionalInfoRequiredStatus
	}

	if m.OnboardingStatus == SystemCheckingOnboardingStatus {
		return SystemCheckInProgressStatus
	}

	return PreparingStatus
}

func (m *Resource) GetCheckFailMsg() string {
	if m.OnboardingStatus == ResourceNotHostStatus ||
		m.OnboardingStatus == NoGPUOnboardingStatus ||
		m.OnboardingStatus == GPUTypeNotUniqueOnboardingStatus ||
		m.OnboardingStatus == UnsupportedOSOnboardingStatus ||
		m.OnboardingStatus == SpecMismatchOnboardingStatus ||
		m.OnboardingStatus == SpecCheckFailedOnboardingStatus || m.OnboardingStatus == IPCheckFailedOnboardingStatus || m.OnboardingStatus == RegistrationLocationOnboardingStatus {
		if text, ok := OnboardingStatusText[m.OnboardingStatus]; ok {
			return text
		}
	}

	return ""
}

type SshSpec struct {
	SSHPrivateKey string `json:"sshKey"  `
	SSHUser       string `json:"user"   `
	NatType       int    `json:"natType"`
	PublicIp      string `json:"publicIp"`
}

var EventSqlField = "rid,resource_type,tid,spec,alias_name,tag,location "
