// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// service session
type ResourceSession struct {
	Sid             int64     `gorm:"column:sid;primary_key;AUTO_INCREMENT"`
	Rid             int64     `gorm:"column:rid;default:0;NOT NULL"`               // pod ID
	Spec            string    `gorm:"column:spec;NOT NULL"`                        // 容器规格
	SessionType     int       `gorm:"column:session_type;default:0;NOT NULL"`      // 会话id（0:render， 1:ai)
	Status          string    `gorm:"column:status;NOT NULL"`                      // current state
	ErrorCode       int       `gorm:"column:error_code;default:0;NOT NULL"`        // error code
	ErrorMsg        string    `gorm:"column:error_msg;NOT NULL"`                   // 出错信息
	Tid             int64     `gorm:"column:tid;default:0;NOT NULL"`               // TENANT ID
	Uid             string    `gorm:"column:uid;NOT NULL"`                         // 用户id
	AppID           int64     `gorm:"column:app_id;default:0;NOT NULL"`            // The ID of the game running on the pod, 0 if there is no game
	ClientIP        string    `gorm:"column:client_ip;NOT NULL"`                   // Client IP
	NoInputTimeouts int       `gorm:"column:no_input_timeouts;default:0;NOT NULL"` // No operation timeout
	TaskID          string    `gorm:"column:task_id"`                              // task id
	UpdateAt        time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP"`
	CreateAt        time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP"`
}

func (m *ResourceSession) TableName() string {
	return "resource_session"
}

