// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// 资源订单表
type ResourceRevcer struct {
	ID          int64     `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	OrderCode   string    `gorm:"column:order_code;default:0;NOT NULL"`   // 订单代码
	RevcerOrder string    `gorm:"column:revcer_order;default:0;NOT NULL"` // 退订订单号
	RevcerTime  int       `gorm:"column:revcer_time;default:0;NOT NULL"`  // 订单退订时间
	Status      int       `gorm:"column:status;default:1;NOT NULL"`       // 0:回收中 1:回收完成
	Rid         int64     `gorm:"column:rid;default:0;NOT NULL"`          // 资源id
	CreateAt    time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt    time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *ResourceRevcer) TableName() string {
	return "resource_revcer"
}

