// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	libModel "github.com/2JYK2/go-lib/models"
	"time"
)

// 资源订单表
type ResourceOrder struct {
	ID                  int64                 `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Tid                 int64                 `gorm:"column:tid;NOT NULL"`                              // order Tid
	OrderCode           string                `gorm:"column:order_code;NOT NULL"`                       // 订单代码
	ResourceType        libModel.ResourceType `gorm:"column:resource_type;NOT NULL"`                    // 资源类型
	OrderType           OrderType             `gorm:"column:order_type;NOT NULL"`                       // 默认0 [0:根据区域订购(tid和cids可以为空)，1:根据tid订购（tid，region，spec, count 不能为空），2:根据hid订购(hids不能为空，其他都可以为空)]
	OrderCreateType     OrderCreateType       `gorm:"column:order_create_type;NOT NULL"`                // 订单创建人 0:普通租户 1:admin 2:特殊租户
	BusinessType        BusinessType          `gorm:"column:business_type;NOT NULL"`                    // 0:IDC 1 :HE
	OrderVersion        OrderVersion          `gorm:"column:order_version;NOT NULL"`                    // 订单版本号
	ThirdPartyOrderCode string                `gorm:"column:third_party_order_code;default:0;NOT NULL"` // 订单关联的三方业务订单编码
	EffectTime          int64                 `gorm:"column:effect_time;default:0;NOT NULL"`            // 订单生效时间，表示状态更改为服务中的时间
	EndTime             int64                 `gorm:"column:end_time;default:0;NOT NULL"`               // 订单结束时间
	RevcerOrder         string                `gorm:"column:revcer_order;default:0;NOT NULL"`           // 退订订单号
	RevcerTime          int                   `gorm:"column:revcer_time;default:0;NOT NULL"`            // 订单退订时间
	Status              OrderStatus           `gorm:"column:status;NOT NULL"`                           // 长租订单状态 0:init 1:paying 2:in service 3:terminal 4:ended 5:资源回收中
	UpdateChecker       string                `gorm:"column:update_checker;default:0;NOT NULL"`         // 退订订单号
	OrderPeriod         int                   `gorm:"column:order_period;default:0;NOT NULL"`           // 订购周期 1:周 2:月 3: 日 4: 年
	ServiceDuration     int                   `gorm:"column:service_duration;NOT NULL"`                 // 订单产品服务时长
	ResourceRequire     string                `gorm:"column:resource_require;NOT NULL"`                 // 订单资源需求清单
	AutoRenew           int                   `gorm:"column:auto_renew;NOT NULL"`                       // 自动续订
	IsCredit            int                   `gorm:"column:is_credit;NOT NULL"`                        // 时否授信订单
	CreateAt            time.Time             `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt            time.Time             `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *ResourceOrder) TableName() string {
	return "resource_order"
}

type OrderStatus int

const (
	OrderInit       OrderStatus = 0 //To Be Paid --未付款
	OrderPaying     OrderStatus = 1 // 支付中，未完成扣款及资源绑定
	OrderCompleted  OrderStatus = 2 // 订单正常结束
	OrderInService  OrderStatus = 3 // 订单服务中
	OrderCanceled   OrderStatus = 4 // 用户侧取消
	OrderTerminated OrderStatus = 5 // 平台侧取消 管理员取消订单||授信订单扣费失败
	OrderFailed     OrderStatus = 6 // 订单创建失败 付款超时 || 扣费失败 || 自动续约失败 ||绑定资源失败
)

type OrderType int

const (
	ContainerOrder OrderType = 0
	SpecialOrder   OrderType = 1
	HostOrder      OrderType = 2
)

type BusinessType int

const (
	FeeBusinessType   BusinessType = 0
	HEFeeBusinessType BusinessType = 1
)

type OrderCreateType int

const (
	TenantSelfCreate    OrderCreateType = 0
	AdminCreate         OrderCreateType = 1
	SpecialTenantCreate OrderCreateType = 2
)

type OrderVersion string

const (
	OrderVersionV2 OrderVersion = "V2"
	OrderVersionV3 OrderVersion = "V3"
)
