// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"encoding/json"
	"time"
)

type ResourceSysInfo struct {
	Rid      int64     `gorm:"column:rid;primary_key;"`         // resource Id  不要显性设置default:0，会有bug https://www.jianshu.com/p/1f266d825bcc
	PubKey   string    `gorm:"column:checker_pub_key;NOT NULL"` // pubilc key
	Details  string    `gorm:"column:details;NOT NULL"`         // host sysinfo
	PriKey   string    `gorm:"column:ssh_pri_key;NOT NULL"`
	SSHUser  string    `gorm:"column:ssh_user;NOT NULL"`
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *ResourceSysInfo) TableName() string {
	return "resource_sys_info"
}

const ResourceSysInfoTableName = "resource_sys_info"

func (m *ResourceSysInfo) DetailToJson() *SysInfo {
	var sysInfo *SysInfo
	_ = json.Unmarshal([]byte(m.Details), &sysInfo)

	return sysInfo
}

type SysInfo struct {
	OSVersion    string         `json:"osVersion"`
	OSStartTs    int64          `json:"osStartTs"`
	AgentVersion string         `json:"agentVersion"`
	OSMem        int64          `json:"osMem"`
	CPUSpec      *CPUInfo       `json:"cpuSpec"`
	Disk         string         `json:"disk"`
	GPUList      []*GPUInfo     `json:"gpuList"`
	NetcardList  []*NetcardInfo `json:"netcardList"`
	SpeedSpec    *SpeedSpec     `json:"speedSpec"`
	Ext          Ext            `json:"ext"`
}

type SpeedSpec struct {
	UploadSpeed   float64 `json:"uploadSpeed"`
	DownloadSpeed float64 `json:"downloadSpeed"`
}
type Ext struct {
	MachineType string `json:"machineType"`
	VtName      string `json:"vtName"`
}

// CPUInfo represents CPU related information
type CPUInfo struct {
	CPUNum          int     `json:"cpuNum"`
	CPUType         string  `json:"cpuType"`
	CPUManufacturer string  `json:"cpuManufacturer"`
	CPUArchitecture string  `json:"cpuArchitecture"`
	CPUCores        int     `json:"cpuCores"`
	CPUThreads      int     `json:"cpuThreads"`
	CPUBaseSpeed    float32 `json:"cpuBaseSpeed"`
}

// DiskInfo represents Disk related information
type DiskInfo struct {
	SizeFree  int64  `json:"sizeFree"`
	SizeTotal int64  `json:"sizeTotal"`
	DiskType  string `json:"diskType"`
}

// GPUInfo represents GPU related information
type GPUInfo struct {
	GPUType         string `json:"gpuType"`
	GPUManufacturer string `json:"gpuManufacturer,omitempty"`
	GPUMem          int    `json:"gpuMem,omitempty"`
	GPUBusType      string `json:"gpuBusType,omitempty"`
	GPUDeviceID     string `json:"gpuDeviceId,omitempty"`
	GPUBusId        string `json:"gpuBusId,omitempty"`
	GpuCount        int    `json:"gpuCount"`
}

// NetcardInfo represents Network Card related information
type NetcardInfo struct {
	NetcardName      string `json:"netcardName"`
	NetcardType      string `json:"netcardType"`
	NetcardLinkSpeed int64  `json:"netcardLinkSpeed"`
}

//func GetBandwidthLevel(s *SpeedSpec) string {
//	bandwidthConfig := config.GetConfig().ServerConfig.CrmConfig.BandwidthConfig
//
//	num := len(bandwidthConfig)
//	for index, item := range bandwidthConfig {
//		if index == 0 && s.UploadSpeed >= item.Upload && s.DownloadSpeed >= item.Download {
//			return item.Level
//		}
//
//		if index != 0 && s.UploadSpeed >= item.Upload && s.DownloadSpeed >= item.Download &&
//			s.UploadSpeed < bandwidthConfig[index-1].Upload && s.DownloadSpeed < item.Download {
//			return item.Level
//		}
//	}
//
//	return bandwidthConfig[num-1].Level
//}
