// Code generated by sql2gorm. DO NOT EDIT.
package crmModel

import (
	"time"
)

// 容器规格能力等级定义
type SpecInfo struct {
	ID              int             `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Spec            string          `gorm:"column:spec;NOT NULL"`                // speCode规格 ,创建时输以空母+数字表示
	BizType         int             `gorm:"column:biz_type;default:0;NOT NULL"`  // Business type[0:ARS 1:Ai]
	Desc            string          `gorm:"column:desc;NOT NULL"`                // 规格描述
	GpuType         string          `gorm:"column:gpu_type;NOT NULL"`            // GPU
	GpuCount        string          `gorm:"column:gpu_count;default:0;NOT NULL"` // GPU 数量
	CpuArchitecture CpuArchitecture `gorm:"column:cpu_architecture;NOT NULL"`    // CPU
	CpuCores        int             `gorm:"column:cpu_cores;default:0;NOT NULL"` // cpu 核数
	CheckRule       string          `gorm:"column:check_rule;NOT NULL"`          // 检测要求
	CheckPaasRule   string          `gorm:"column:check_paas_rule;NOT NULL"`     // 检测通过要求
	CreateChannels  string          `gorm:"column:create_channels;NOT NULL"`     // 创建方式
	PL              string          `gorm:"column:pl;NOT NULL"`                  // 创建方式
	IsDelete        int             `gorm:"column:is_delete;default:0;NOT NULL"` // 是否删除
	CreateAt        time.Time       `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt        time.Time       `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *SpecInfo) TableName() string {
	return "spec_info"
}

type CpuArchitecture string

const (
	ARM CpuArchitecture = "arm"
	X86 CpuArchitecture = "x86"
)
