// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

type ConfigClientType struct {
	ClientType              int       `gorm:"column:client_type;primary_key" json:"client_type"`                                    // Terminal TypeID,MOBILE_ANDROID:1,MOBILE_IOS:2,MOBILE_WEB:3, PC_MAC:4, PC_WIN:5, PC_WEB:6, TV_ANDROID:7, VR_ANDROID:8
	ClientName              string    `gorm:"column:client_name;NOT NULL" json:"client_name"`                                       // Terminal Type,MOBILE_ANDROID,MOBILE_IOS,MOBILE_WEB, PC_MAC, PC_WIN, PC_WEB, TV_ANDROID, VR_ANDROID
	SupportVideoTypes       string    `gorm:"column:support_video_types" json:"support_video_types"`                                // Supported video types and generation order in SDPOffer, separated by commas, including: h.265, h.264, vp8
	SupportAudioTypes       string    `gorm:"column:support_audio_types" json:"support_audio_types"`                                // Audio type, multiple separated by commas, including: aac, opus
	EnableDrawMouse         int       `gorm:"column:enable_draw_mouse" json:"enable_draw_mouse"`                                    // Whether to enable terminal mouse drawing
	Note                    string    `gorm:"column:note" json:"note"`                                                              // memo
	CreateAt                time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"`                 // Data record creation time
	UpdateAt                time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"`                 // Data update time
	EnableEnhanceResolution int       `gorm:"column:enable_enhance_resolution;default:0;NOT NULL" json:"enable_enhance_resolution"` // Whether to enable resolution superresolution
	MaxResoLevel            string    `gorm:"column:max_reso_level;NOT NULL" json:"max_reso_level"`                                 // Maximum decoding clarity level supported
}

func (m *ConfigClientType) TableName() string {
	return "config_client_type"
}

