// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

// Container scheduling quantity configuration
type ConfigContainerScheduler struct {
	ID             int64     `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Tid            int64     `gorm:"column:tid;default:0;NOT NULL" json:"tid"`                         // Tenant ID
	RegionCode     string    `gorm:"column:region_code;NOT NULL" json:"region_code"`                   // Region code
	AppID          int64     `gorm:"column:app_id;default:0;NOT NULL" json:"app_id"`                   //
	SchedulerLimit int       `gorm:"column:scheduler_limit;default:0;NOT NULL" json:"scheduler_limit"` // Scheduling restrictions
	WarnRate       int       `gorm:"column:warn_rate;default:0;NOT NULL" json:"warn_rate"`             // Alarm ratio
	CreateAt       time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"`
	UpdateAt       time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"`
}

func (m *ConfigContainerScheduler) TableName() string {
	return "config_container_scheduler"
}

