// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

type ConfigRtc struct {
	ID         int       `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Tid        int64     `gorm:"column:tid;default:0;NOT NULL" json:"tid"`                 // Tenant id
	Appid      int64     `gorm:"column:appid;default:0;NOT NULL" json:"appid"`             // App id
	ClientType int       `gorm:"column:client_type;default:0;NOT NULL" json:"client_type"` // Client type
	RegionCode string    `gorm:"column:region_code;NOT NULL" json:"region_code"`           // Region code
	Rtc        string    `gorm:"column:rtc;NOT NULL" json:"rtc"`                           // Rtc config
	CreateAt   time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt   time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP" json:"update_at"`
}

func (m *ConfigRtc) TableName() string {
	return "config_rtc"
}
