// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

type ConfigClientSdk struct {
	ID            uint      `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	ClientModel   string    `gorm:"column:client_model;NOT NULL"`
	ClientType    int       `gorm:"column:client_type;default:0;NOT NULL"`    // Client type
	EnableDebug   int       `gorm:"column:enable_debug;default:0;NOT NULL"`   // Whether to enable debug mode
	Tid           int64     `gorm:"column:tid;default:0;NOT NULL"`            // Tenant ID, greater than 0 represents the specific tenant, controlling the corresponding sdk configuration
	Uid           string    `gorm:"column:uid;NOT NULL"`                      // User ID, not empty, represents the client-specific user ID controlling the sdk configuration parameters
	UploadRunLog  int       `gorm:"column:upload_run_log;default:0;NOT NULL"` // Whether to upload sdk running log
	RtcLibConfig  string    `gorm:"column:rtclib_config;NOT NULL"`            // Client SDK's webrtclib library configuration information
	DecoderConfig string    `gorm:"column:decoder_config;NOT NULL"`           // Client decoder configuration information
	CreateAt      time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt      time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *ConfigClientSdk) TableName() string {
	return "config_client_sdk"
}
