// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)


type ConfigContainerSpec struct {
	ID         int       `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	PowerLevel string    `gorm:"column:power_level;NOT NULL"`         // power level name, A B C D
	PowerValue int       `gorm:"column:power_value;NOT NULL"`         // Ability level value, the larger the value, the higher the ability level, 8:A,  4:B,  2:C,  1:D
	Spec       string    `gorm:"column:spec;NOT NULL"`                // name
	ArsType    string    `gorm:"column:ars_type;NOT NULL"`            // Container type, W: Windows,  A: ARM
	PowerCpu   int       `gorm:"column:power_cpu;NOT NULL"`           // CPU ability value
	PowerGpu   int       `gorm:"column:power_gpu;NOT NULL"`           // GPU rendering ability value
	PowerVpu   int       `gorm:"column:power_vpu;default:0;NOT NULL"` // Encoding engine ability value, reported by ARSDog
	PowerMem   int       `gorm:"column:power_mem;default:0;NOT NULL"` // Memory ability value, MB
	PowerGmem  int       `gorm:"column:power_gmem;default:0;NOT NULL"`
	PowerDisk  int       `gorm:"column:power_disk;default:0;NOT NULL"` // Disk ability value, SSD: 2000, HDD: 1000
	CreateAt   time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt   time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
}

func (m *ConfigContainerSpec) TableName() string {
	return "config_container_spec"
}
