// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	libModel "github.com/2JYK2/go-lib/models"
	"time"
)

// Container Subtable
type Server struct {
	AutoID          int64           `gorm:"column:auto_id;primary_key;AUTO_INCREMENT" json:"autoID"`
	ID              int64           `gorm:"column:id" json:"id"`
	RegionCode      string          `gorm:"column:region_code;NOT NULL" json:"regionCode"`                   // Region code
	Name            string          `gorm:"column:name;NOT NULL" json:"name"`                                // Machine name
	Fingerprint     string          `gorm:"column:fingerprint;NOT NULL" json:"fingerprint"`                  // Machine fingerprint, unique identifier generated using tenant ID and machine MAC address
	TID             int64           `gorm:"column:tid;default:0;NOT NULL" json:"tid"`                        // Tenant ID
	Mac             string          `gorm:"column:mac;NOT NULL" json:"mac"`                                  // MAC address of the server's first network card
	SN              string            `gorm:"column:sn;NOT NULL" json:"sn"`
	ResourcePool    string          `gorm:"column:resource_pool;NOT NULL" json:"resourcePool"`               // Resource type ARS BM HE Contract
	ServerRole      ServerRole      `gorm:"column:server_role;NOT NULL" json:"serverRole"`                   // Server role, manually specified
	OsType          libModel.OsType `gorm:"column:os_type;default:windows;NOT NULL" json:"osType"`           // Container system type, windows, android
	OsStartAt       int64           `gorm:"column:os_start_at;default:0;NOT NULL" json:"osStartAt"`          // Timestamp of the most recent OS startup
	ArsMgrStartTs   int64           `gorm:"column:ars_mgr_start_ts;default:0;NOT NULL" json:"arsMgrStartTs"` // Timestamp of the most recent OS startup
	CpuType         string          `gorm:"column:cpu_type;NOT NULL" json:"cpuType"`                         // CPU model
	CpuCount        int             `gorm:"column:cpu_count;default:0;NOT NULL" json:"cpuCount"`             // Number of CPU threads
	GpuType         string          `gorm:"column:gpu_type;NOT NULL" json:"gpuType"`                         // GPU model
	LocalIP         string          `gorm:"column:local_ip;NOT NULL" json:"localIP"`                         // Local IP
	LocalPort       int             `gorm:"column:local_port;default:0;NOT NULL" json:"localPort"`           // Local port
	ArsDogConnAddr  string          `gorm:"column:ars_dog_conn_addr;NOT NULL" json:"arsDogConnAddr"`         // Long connection node IP between arsDog module and registerSvc
	UpdateChecker   string          `gorm:"column:update_checker;NOT NULL" json:"updateChecker"`             // Optimistic lock for data update operations
	CreateAt        time.Time       `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"createAt"`
	UpdateAt        time.Time       `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"updateAt"`
	DeleteAt        int64           `gorm:"column:delete_at;default:0;NOT NULL" json:"deleteAt"`
	HostServer      string          `gorm:"column:host_server;NOT NULL" json:"hostServer"`           // Host server fingerprint, belongs to host container management, this field is a concern for host container management
	PlatformSubtype string          `gorm:"column:platform_subtype;NOT NULL" json:"platformSubtype"` // Platform subtype
	CheckStatus     string          `gorm:"column:check_status;NOT NULL" json:"check_status"`        // Check status
	LastCheckTS     int64           `gorm:"column:last_check_ts;NOT NULL" json:"last_check_ts"`      // Last check timestamp

}

func (s *Server) TableName() string {
	return "server"
}

type ServerRole string

const (
	ARS          ServerRole = "ars"
	Storage      ServerRole = "storage"
	OverlayAgent ServerRole = "overlay-agent"
	Host         ServerRole = "host"
)
