// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

// Container Subtable
type ServerSublist struct {
	Cid                int64     `gorm:"column:cid;default:0;NOT NULL" json:"cid"`
	Fingerprint        string    `gorm:"column:fingerprint;primary_key" json:"fingerprint"`                            // Machine fingerprint, unique identifier, generated by taking the Md5 of tenant ID and machine MAC address
	RegionCode         string    `gorm:"column:region_code;NOT NULL" json:"region_code"`                               // Region
	BizType            int       `gorm:"column:biz_type;default:0;NOT NULL" json:"biz_type"`                           // Business type (0 for cloud gaming, 1 for cloud desktop, 2 for both cloud gaming and cloud desktop)
	WholeSaleTid       int64     `gorm:"column:whole_sale_tid;default:0;NOT NULL" json:"whole_sale_tid"`               // Tenant ID of the container order
	Online             int       `gorm:"column:online;default:0;NOT NULL" json:"online"`                               // Online status
	NatIP              string    `gorm:"column:nat_ip;NOT NULL" json:"nat_ip"`                                         // NAT IP v4
	StakeStatus        int       `gorm:"column:stake_status;default:0;NOT NULL" json:"stake_status"`                   // Stake status (0 for Normal, 1 for Staking, 2 for Unstaking)
	NatPort            int       `gorm:"column:nat_port;default:0;NOT NULL" json:"nat_port"`                           // External network port
	SignalSvcLocalPort int       `gorm:"column:signal_svc_local_port;default:0;NOT NULL" json:"signal_svc_local_port"` // WebRTC local port for signaling interaction
	SignalSvcNatPort   int       `gorm:"column:signal_svc_nat_port;default:0;NOT NULL" json:"signal_svc_nat_port"`     // WebRTC external port for signaling interaction
	Spec               string    `gorm:"column:spec;NOT NULL" json:"spec"`                                             // Specification name
	OrderCode          string    `gorm:"column:order_code;default:0;NOT NULL" json:"order_code"`                       // Long-term order number
	Tag                string    `gorm:"column:tag;NOT NULL" json:"tag"`                                               // Container tag
	CreateAt           time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"create_at"`
	UpdateAt           time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL" json:"update_at"`
	NatIPV4            string    `gorm:"column:nat_ip_v4;NOT NULL" json:"nat_ip_v4"`                                   // NAT IP v4 (deprecated in version 1.6.2)
	SshPort            int       `gorm:"column:ssh_port;default:22;NOT NULL" json:"ssh_port"`                          // SSH port
	NatIPV6            string    `gorm:"column:nat_ip_v6;NOT NULL" json:"nat_ip_v6"`                                   // NAT IP v6 (deprecated in version 1.6.2)
}

func (m *ServerSublist) TableName() string {
	return "server_sublist"
}