// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

type TenantAksk struct {
	ID       int64     `gorm:"column:id;primary_key;AUTO_INCREMENT"` // Unique auto increment ID
	Tid      int64     `gorm:"column:tid;NOT NULL"`
	Name     string    `gorm:"column:name"`            // Access key identifier
	Note     string    `gorm:"column:note"`            // Access key description
	Ak       string    `gorm:"column:ak"`              // Access key
	Sk       string    `gorm:"column:sk"`              // Secret key
	Valid    int       `gorm:"column:valid;default:1"` // Whether available
	EffectTs time.Time `gorm:"column:effect_ts"`       // Effective timestamp, seconds
	ExpireTs time.Time `gorm:"column:expire_ts"`       // Expiration timestamp, seconds
	RoleID   int       `gorm:"column:role_id"`         // Role ID that the access key belongs to, determining the API access range
	CreateAt time.Time `gorm:"column:create_at"`
	UpdateAt time.Time `gorm:"column:update_at"`
}

func (m *TenantAksk) TableName() string {
	return "tenant_aksk"
}
