// Code generated by sql2gorm. DO NOT EDIT.
package mgrModel

import (
	"time"
)

type TenantInfo struct {
	ID                  int64     `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Code                string    `gorm:"column:code"`
	Name                string    `gorm:"column:name;NOT NULL"`        // Tenant name
	Status              string    `gorm:"column:status;NOT NULL"`      // Tenant status, regist: registration status, submit_auth: submitted authentication status, normal: normal audited status, freeze: frozen status
	TenantType          string    `gorm:"column:tenant_type;NOT NULL"` // Tenant type, GP: game provider, IDC: container provider,  master account, GPD: game developer
	CreateAt            time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	UpdateAt            time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;NOT NULL"`
	Address             string    `gorm:"column:address"`                        // Wallet address
	CallbackUrl         string    `gorm:"column:callback_url;NOT NULL"`          // Event callback URL
	EnableThirdStreamer bool      `gorm:"column:enable_third_streamer;NOT NULL"` // Whether it is a third-party streaming platform
}

func (m *TenantInfo) TableName() string {
	return "tenant_info"
}