package gpuSchedulerModel

// Code generated by sql2gorm. DO NOT EDIT.

import (
	"time"
)

// gpu session list
type GpuSession struct {
	Sid            int64     `gorm:"column:sid;primary_key;default:0" json:"sid"`                        // sid
	TaskID         int64     `gorm:"column:task_id;default:0;NOT NULL" json:"task_id"`                   // pod ID
	GpuID          int64     `gorm:"column:gpu_id;default:0;NOT NULL" json:"gpu_id"`                     // pod ID
	GpuType        string    `gorm:"column:gpu_type;NOT NULL" json:"gpu_type"`                           // gpu type
	ModelID        int       `gorm:"column:model_id;default:0;NOT NULL" json:"model_id"`                 // 模型id
	ModelVersionID int       `gorm:"column:model_version_id;default:0;NOT NULL" json:"model_version_id"` // 模型版本id
	Status         GpuStatus `gorm:"column:status;NOT NULL" json:"status"`                               // current state
	ErrorCode      int       `gorm:"column:error_code;default:0;NOT NULL" json:"error_code"`             // error code
	ErrorMsg       string    `gorm:"column:error_msg;NOT NULL" json:"error_msg"`                         // 出错信息
	Uid            string    `gorm:"column:uid;NOT NULL" json:"uid"`                                     // 用户id
	ClientIP       string    `gorm:"column:client_ip;NOT NULL" json:"client_ip"`                         // Client IP
	ByTest         int       `gorm:"column:by_test;default:0;NOT NULL" json:"by_test"`                   // Whether to test the scenario
	StartAt        int64     `gorm:"column:start_at;default:0;NOT NULL" json:"start_at"`                 // 开始时间
	EndAt          int64     `gorm:"column:end_at;default:0;NOT NULL" json:"end_at"`                     // 结束时间
	UpdateAt       time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateAt       time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP" json:"create_at"`
}

func (m *GpuSession) TableName() string {
	return "gpu_session"
}
